# Generated by Django 4.2.25 on 2025-10-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='studio_name',
        ),
    ]
